edition = "2021"
unstable_features = true
max_width = 100
group_imports = "StdExternalCrate"
imports_granularity="Crate"
wrap_comments = true
format_code_in_doc_comments = true
use_try_shorthand = true
use_field_init_shorthand = true